// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqlzwswqxolaezhqbswf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxbHp3c3dxeG9sYWV6aHFic3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTI0ODUsImV4cCI6MjA2OTg4ODQ4NX0.ojB7_pIh75wIJjGV4sPaXMAihRRlvp_n0aqXZug79yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});